# Blog settings
permalink: /:year/:month/:title
url: http://h01000110.github.io

# My variables
name: hi
description: Desenvolvimento e Aprendizado
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

og_locale: "pt_BR"
disqus_shortname: "h01000110"
twitter_username: "h01000110"
twitter_card: "summary_large_image"
twitter_site: "@h01000110"

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
